// Generated by CoffeeScript 1.10.0
(function() {
  var extension, fs;

  fs = require('fs');

  extension = "." + process.argv[3];

  fs.readdir(process.argv[2], function(error, files) {
    var file, i, len, results;
    results = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      if (file.endsWith(extension)) {
        results.push(console.log(file));
      } else {
        results.push(void 0);
      }
    }
    return results;
  });

}).call(this);
